server:
  servlet:
    context-path: 
  port: ${PORT:9000}

spring:
  datasource:
    url: jdbc:postgresql://ec2-174-129-255-69.compute-1.amazonaws.com:5432/dd888ee0l4hno5
    username: nyesztwgkaybqa
    password: 292dac9cc378167594acb49d463b60b7872ffeee290c459c93d4b021c5a0af5c
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: ${HIBERNATE_SHOW_SQL:false}
    properties:
      hibernate:
        generate_statistics: ${HIBERNATE_STATISTICS:false}
        temp:
          use_jdbc_metadata_defaults: false

oauth2-config:
  client-id: ${CLIENT_ID:76179baad962d1b8ce4d}
  client-secret: ${CLIENT_SECRET:8faedc0e6e1520d13f06f787d6760c303f3e8768}
  server-url: ${OAUTH2_URL:https://development-oauth-server.herokuapp.com}

depara:
  service:
    name: depara-service
    url: ${DEPARA_BASE_URL:https://development-api-depara.herokuapp.com}

oauth:
  service:
    name: oauth-service
    url: ${OAUTH2_URL:https://development-oauth-server.herokuapp.com}

security:
  oauth2:
    client:
      clientId: ${oauth2-config.client-id}
      clientSecret: ${oauth2-config.client-secret}
      accessTokenUri: ${oauth2-config.server-url}/oauth/token
      userAuthorizationUri: ${oauth2-config.server-url}/oauth/authorize

    resource:
      userInfoUri: ${oauth2-config.server-url}/user/info
      tokenInfoUri: ${oauth2-config.server-url}/oauth/check_token